//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class avatar
    {
        public avatar()
        {
            this.users = new HashSet<user>();
        }
    
        public long id_Avatars { get; set; }
        public string avatar_src { get; set; }
    
        public virtual ICollection<user> users { get; set; }
    }
}
