//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public city()
        {
            this.users = new HashSet<user>();
        }
    
        public long id_city { get; set; }
        public string city_name { get; set; }
        public long id_country { get; set; }
    
        public virtual country country { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
