//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public @event()
        {
            this.images = new HashSet<image>();
        }
    
        public long id_event { get; set; }
        public string Source { get; set; }
        public long Type_id_Type { get; set; }
    
        public virtual type_of_data type_of_data { get; set; }
        public virtual ICollection<image> images { get; set; }
    }
}
