//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public long id_History { get; set; }
        public long id_user { get; set; }
        public long id_image { get; set; }
        public Nullable<double> history_N { get; set; }
        public Nullable<double> history_E { get; set; }
        public System.DateTime Date_scaning { get; set; }
    
        public virtual user user { get; set; }
        public virtual image image { get; set; }
    }
}
