//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public image()
        {
            this.histories = new HashSet<history>();
            this.stock_and_image = new HashSet<stock_and_image>();
        }
    
        public long id_image { get; set; }
        public Nullable<long> id_properties { get; set; }
        public Nullable<long> id_author { get; set; }
        public Nullable<System.DateTime> publication_date { get; set; }
        public Nullable<long> id_category_image { get; set; }
        public Nullable<long> id_event { get; set; }
        public string Image_src { get; set; }
        public string description_image { get; set; }
        public Nullable<double> image_N { get; set; }
        public Nullable<double> image_E { get; set; }
        public bool isConfirmed { get; set; }
    
        public virtual category_image category_image { get; set; }
        public virtual @event @event { get; set; }
        public virtual ICollection<history> histories { get; set; }
        public virtual user user { get; set; }
        public virtual properties_images properties_images { get; set; }
        public virtual ICollection<stock_and_image> stock_and_image { get; set; }
    }
}
