//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lume_LumeEntities : DbContext
    {
        public lume_LumeEntities()
            : base("name=lume_LumeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<avatar> avatars { get; set; }
        public DbSet<category_image> category_image { get; set; }
        public DbSet<city> cities { get; set; }
        public DbSet<country> countries { get; set; }
        public DbSet<@event> events { get; set; }
        public DbSet<history> histories { get; set; }
        public DbSet<image> images { get; set; }
        public DbSet<prize> prizes { get; set; }
        public DbSet<properties_images> properties_images { get; set; }
        public DbSet<stock> stocks { get; set; }
        public DbSet<stock_and_image> stock_and_image { get; set; }
        public DbSet<stock_prize> stock_prize { get; set; }
        public DbSet<stock_progress> stock_progress { get; set; }
        public DbSet<stock_type> stock_type { get; set; }
        public DbSet<type_of_data> type_of_data { get; set; }
        public DbSet<type_of_prize> type_of_prize { get; set; }
        public DbSet<user_and_stock> user_and_stock { get; set; }
        public DbSet<user> users { get; set; }
    }
}
