//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class prize
    {
        public prize()
        {
            this.stock_prize = new HashSet<stock_prize>();
        }
    
        public long id_prize { get; set; }
        public string prize_description { get; set; }
        public long id_type_prize { get; set; }
        public string prize_data { get; set; }
    
        public virtual type_of_prize type_of_prize { get; set; }
        public virtual ICollection<stock_prize> stock_prize { get; set; }
    }
}
