//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_progress
    {
        public long id_stock_progress { get; set; }
        public long id_user { get; set; }
        public long id_stock_and_Image { get; set; }
        public bool is_scanned { get; set; }
    
        public virtual stock_and_image stock_and_image { get; set; }
        public virtual user user { get; set; }
    }
}
