//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_and_image
    {
        public stock_and_image()
        {
            this.stock_progress = new HashSet<stock_progress>();
        }
    
        public long id_stock_and_image { get; set; }
        public long id_image { get; set; }
        public long id_stock { get; set; }
    
        public virtual image image { get; set; }
        public virtual stock stock { get; set; }
        public virtual ICollection<stock_progress> stock_progress { get; set; }
    }
}
