//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_type
    {
        public stock_type()
        {
            this.stocks = new HashSet<stock>();
        }
    
        public long id_stock_type { get; set; }
        public string stock_type1 { get; set; }
    
        public virtual ICollection<stock> stocks { get; set; }
    }
}
