//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public stock()
        {
            this.stock_prize = new HashSet<stock_prize>();
            this.user_and_stock = new HashSet<user_and_stock>();
            this.stock_and_image = new HashSet<stock_and_image>();
        }
    
        public long id_stock { get; set; }
        public string stock_name { get; set; }
        public long id_author { get; set; }
        public string description_stock { get; set; }
        public System.DateTime date_begin { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public long id_stock_type { get; set; }
    
        public virtual ICollection<stock_prize> stock_prize { get; set; }
        public virtual stock_type stock_type { get; set; }
        public virtual ICollection<user_and_stock> user_and_stock { get; set; }
        public virtual ICollection<stock_and_image> stock_and_image { get; set; }
        public virtual user user { get; set; }
    }
}
