//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_of_data
    {
        public type_of_data()
        {
            this.events = new HashSet<@event>();
        }
    
        public long id_Type { get; set; }
        public string type_data { get; set; }
    
        public virtual ICollection<@event> events { get; set; }
    }
}
