//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_of_prize
    {
        public type_of_prize()
        {
            this.prizes = new HashSet<prize>();
        }
    
        public long id_type { get; set; }
        public string prize_type { get; set; }
    
        public virtual ICollection<prize> prizes { get; set; }
    }
}
