//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.histories = new HashSet<history>();
            this.images = new HashSet<image>();
            this.stocks = new HashSet<stock>();
            this.stock_progress = new HashSet<stock_progress>();
            this.user_and_stock = new HashSet<user_and_stock>();
        }
    
        public long id_user { get; set; }
        public string users_name { get; set; }
        public string users_password { get; set; }
        public string users_email { get; set; }
        public string type_user { get; set; }
        public long id_city { get; set; }
        public string phone_number { get; set; }
        public long id_avatars { get; set; }
        public Nullable<double> users_N { get; set; }
        public Nullable<double> users_E { get; set; }
    
        public virtual avatar avatar { get; set; }
        public virtual city city { get; set; }
        public virtual ICollection<history> histories { get; set; }
        public virtual ICollection<image> images { get; set; }
        public virtual ICollection<stock> stocks { get; set; }
        public virtual ICollection<stock_progress> stock_progress { get; set; }
        public virtual ICollection<user_and_stock> user_and_stock { get; set; }
    }
}
